path: internal/version/.version

plugins:
  changelog-generator:
    enabled: true
    mode: "versioned"
    changes-dir: ".changes"
    use-default-icons: true
    repository:
      auto-detect: true
    exclude-patterns:
      - "^Merge"
      - "^WIP"
      - "^release"
    contributors:
      enabled: true
