name: Release
on:
  release:
    types: [created]

permissions: {}

env:
  GO_VERSION: "1.25"

jobs:
  create-release-notes:
    name: release-notes
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Create Release
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
          GH_TOKEN: ${{ secrets.SLEY_TOKEN }}
        run: |
          gh release edit "$TAG_NAME" \
            --title "$TAG_NAME" \
            --draft=false \
            --prerelease=false \
            --latest \
            --notes-file "${{ github.workspace }}/.changes/${TAG_NAME}.md"

  goreleaser:
    name: goreleaser
    runs-on: ubuntu-latest
    needs: create-release-notes
    permissions:
      contents: write
    environment:
      name: Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: go.sum
          check-latest: true
          cache: false

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
